// Voice guidance script and clip paths. Owner: Labib (tickets L1 and L6).
//
// The clips are pre-generated by scripts/gen-voice.ts and served as static
// files, so the patient flow never waits on a live ElevenLabs call mid-demo.
//
// The challenge code is different per link, so no clip ever says it out loud.
// Every clip points at the code on the screen instead.

export type Language = "en" | "es";

export type CaptureStep = "welcome" | "write_code" | "frame" | "review" | "sent";

export const CAPTURE_STEPS: CaptureStep[] = ["welcome", "write_code", "frame", "review", "sent"];

export const VOICE_SCRIPT: Record<Language, Record<CaptureStep, string>> = {
  en: {
    welcome:
      "Your clinic asked you to take your pregnancy test at home. This takes about two minutes. Take the test first and wait the full time on its box.",
    write_code:
      "Now write the four characters shown on your screen onto the test, near the result window, with a pen.",
    frame:
      "Hold the test flat under good light and fill the frame. Keep the result window and the code you wrote both visible, then take the photo.",
    review:
      "Check that the lines and the code are sharp. If anything is blurry, retake it. When it looks clear, send it.",
    sent: "Received. Your clinic will review it and will be in touch. You can close this page.",
  },
  es: {
    welcome:
      "Su clínica le pidió hacer la prueba de embarazo en casa. Esto toma unos dos minutos. Haga la prueba primero y espere el tiempo completo indicado en la caja.",
    write_code:
      "Ahora escriba con bolígrafo los cuatro caracteres que aparecen en su pantalla sobre la prueba, cerca de la ventana de resultado.",
    frame:
      "Sostenga la prueba plana con buena luz y llene el encuadre. Deje visibles la ventana de resultado y el código que escribió, y luego tome la foto.",
    review:
      "Revise que las líneas y el código se vean nítidos. Si algo está borroso, tome la foto otra vez. Cuando se vea claro, envíela.",
    sent: "Recibido. Su clínica lo revisará y se comunicará con usted. Puede cerrar esta página.",
  },
};

export function clipPath(language: Language, step: CaptureStep): string {
  return `/audio/${language}/${step}.mp3`;
}

/** On-screen text, which is also the fallback if the clips get cut (see PRD). */
export function stepText(language: Language, step: CaptureStep): string {
  return VOICE_SCRIPT[language][step];
}

export const UI_TEXT: Record<Language, Record<string, string>> = {
  en: {
    title: "Home pregnancy test",
    codeLabel: "Write this code on the test",
    start: "Start",
    openCamera: "Open camera",
    takePhoto: "Take photo",
    retake: "Retake",
    send: "Send to my clinic",
    sending: "Sending…",
    sentTitle: "Received",
    cameraBlocked:
      "This page needs your camera. Allow camera access in your browser, then reload. Photos cannot be uploaded from your gallery.",
    linkProblem: "This link cannot be used",
    tryAgain: "Try again",
    stepOf: "Step",
    resume: "Continue",
    starting: "Starting…",
    timeLeft: "Time left",
    startFailed: "Could not start. Check your connection.",
  },
  es: {
    title: "Prueba de embarazo en casa",
    codeLabel: "Escriba este código en la prueba",
    start: "Comenzar",
    openCamera: "Abrir cámara",
    takePhoto: "Tomar foto",
    retake: "Repetir",
    send: "Enviar a mi clínica",
    sending: "Enviando…",
    sentTitle: "Recibido",
    cameraBlocked:
      "Esta página necesita su cámara. Permita el acceso a la cámara en su navegador y recargue. No se pueden subir fotos desde la galería.",
    linkProblem: "Este enlace no se puede usar",
    tryAgain: "Intentar de nuevo",
    stepOf: "Paso",
    resume: "Continuar",
    starting: "Comenzando…",
    timeLeft: "Tiempo restante",
    startFailed: "No se pudo comenzar. Revise su conexión.",
  },
};

/** Why a link cannot be used, by link state (lib/fraud/session.ts). */
export type LinkProblemState = "invalid" | "link_expired" | "session_expired" | "submitted" | "error";

export const LINK_PROBLEM_TEXT: Record<Language, Record<LinkProblemState, string>> = {
  en: {
    invalid: "This link is not valid. Ask your clinic for a new one.",
    link_expired: "This link has expired. Ask your clinic for a new one.",
    session_expired: "Your test session has ended. Ask your clinic for a new link.",
    submitted: "A photo was already sent with this link. Your clinic will be in touch.",
    error: "Something went wrong. Reload the page or contact your clinic.",
  },
  es: {
    invalid: "Este enlace no es válido. Pida uno nuevo a su clínica.",
    link_expired: "Este enlace ha caducado. Pida uno nuevo a su clínica.",
    session_expired: "Su sesión de prueba terminó. Pida un enlace nuevo a su clínica.",
    submitted: "Ya se envió una foto con este enlace. Su clínica se comunicará con usted.",
    error: "Algo salió mal. Recargue la página o contacte a su clínica.",
  },
};
